### ISSUE TITLE
missing tags on git repo to match the forge. 

### ISSUE THREAD

**Issue by brettswift** [grundic/puppet-teamcity#9]
This is good for two reasons: 

1) some clone from git and not the forge, using r10k for example.
2) If you are using the forge module and you find a bug, you surely want to know what version to link back to git. 

It'd probably be sufficient to just tag the latest release and not do them retroactively. 

Other than that this looks like it's a decent module - we might use it! 

Thanks

**Comment by grundic** [comment]
@brettswift, thank you for your feedback!
I agree, tagging releases is good idea, will do it soon.

**Comment by grundic** [comment]
Added tag for new version.
